sudo: required
language: bash
services:
- docker
script:
- sh build.sh

deploy:
 - provider: s3
   access_key_id:
     secure: RY4Ibctdr/020yuDcghXzcgBuwLVfBZbRUD6d5GkUHLIRSoV0Ylww8IKHg7nZRFoI5HcqhXB5jAEf/MDEKDddnqBLyJDapqohxk2lHe3tkTe42dyfoRz6bIKqoTWgtxTu7mZNILYZ8hba5ENLhGHKUszbIphCIXBnDhmBO9Hjcomv8YNG0zIiCJZ/ZD6vRaehHDfIVJZVHw8z00pfyByNbWCsJIME4/+NAXKbqjyddlV/5OXdeyP5/YuRTT1S72uFK8DfQ54gJkV/j/afhFPs5HP5KEFNUAldYSz0ADq0EWXSKXIhwjzibTtMN8nF8R7kIJu5LRMCwKZxNP05vSl7ZJbUKP3El9lTzydDGES/u/9YW++u6ff6vHo8wcJ04znU6rB9n5CurqKkRu49pY2uJhNFCJm9JJROotwOpddCyAuB1UVehTZj8qfezIG7aDdBtdS6ASGSIQms0+9S2k0gf+T16WZijQ8h3ksqEj4Cd6Nkx8X7uuFUJl+oBXt/ZQXIpx/0smQw2C6SX8aWH6ULh8The2HSkA8oeVb5InM3nRlifn/QFvXlXFtGo5TcTLc50p3goHufOlNfNoTYqen55vpsoELB918zrC7ZjfG/4pPEDFhkJOMfSacfrGuQ3Ecrebu9yI7CKwUzp/9YF2OJnoxA/fAw4mmkFLwl3/bI1E=
   secret_access_key:
     secure: J8fFryEMB3t1QxafOLoZpDpKRmpJWDESq525l6Ozdvy8rrhz6bIxRGZYgLe8mbciZWaSgYo4MM/k1ovWm/ibidmibmLDcRt+QQqezBYLBDg6Gs13Yn6kgdjEvIFxEeAYNcxax0fGBPZnaKAMgGx9XP4bwWuNxEoZKDrC/HcQE8qifmnXFPUw+pIcseTnb5fqAIZfu1IM9QXNgHYjUP1zW9C7A3DtzoJgNtkuB/DkPp6QxkEoro0AufHOKD1Dli2z8D9wDvZWNIWndyjchbmCzk7FrBrUKFkbAi6EeSU6ZSEa7Hn0maQU1YZhuZANp5LXnxxq5SlcVjF9FhyV6O+A+I1TnNu9gmww7gfS0ZSwp2b/6j2d92/BKRp1J+64jpPXSjfAIstbIJQWSCfd0fogwIFjpzZ0/z86dngmMKJJcA4HXA73NypBhh0CVDBkK1lYFl5s095OPLTZ9qNSJjYaXm7k45fy9o+NhPXDdLECog+72vKd89sCTnFt57LHHP32lYD6WBNDrx3W/e2Tn5jlvhKj7p9T5PHfbKEPquetj9NgZkjCleJ4X9QoUOg2jO0ctwu2OGOwVRTIz/gAK6NIOvGaY3RocmkvPcoY4xJz9xQv9/Og50qkPK9mpuY1g/zwGIBc72doDSOp90h8G5/zhEiMPgp4FNUlCwybmIIaN8s=
   bucket:
     secure: M4LsdUF4xuJ7jY8d+i709ZpdJLzsnoHjccbHwUd4JYxPRh6292IJA2LEcIuOSV2ySWTHWvQnp1rPeQP5UO4vSngh0PmZtMh9Ch9EMNXXV9UrD2vghtq+NJLewWGNn6wkxV3I2EsixrFqo8008LEQdPt7GtIAz0kbhnQEjjSVrND/acGL0286oJFvQfw997wzhGnH7pSEPF4PDTEnYevn3XXZQFxplzIgcmu43t+DgDwNy89WXuZtZYyhe/dEN3NnDqtMs+10eWeciS21ygHR/h+Q4p7fXI9Q1lO705bS//lV7s+M7mm8BL5ppWBkKxjkckN3oPYtQGlUInOXh3JQQAbG7jJFBdRwa18FlsN8LwnSMFJAH1e9Nd88RWem/DynwvAhFJ5iWUJN8tBsx9djyukqxhEOuMC3x5QAODIZhwraarsP7LUZPR+SriB8KAOMzX+WNZEGRLIp3yIJN4J3McrUKDAVh7Em7q80Kpnf9kf7mCfidCXVQ1XC7b8HnLESNDtNwb1GtteNBfLUq3R04TJJ6vGedOVAJbDTrTDcTg4//qezuf6ICfcITV9gJNP1YfSuBHLV+sgqkUYvPCsKvizfUZmoupobG4G+RT+cDAiIfBe9/Ja8NrHUWdKzKeXXjOpnx3cPqIuvXfVs0bwepusCs9g2dOcvWVvDY2cmh90=
   region: eu-west-1
   local-dir: target/site
   upload-dir: poacc/upgrade-3
   acl: public_read
   skip_cleanup: true
   on:
    repo: OpenPEPPOL/poacc-upgrade-3
    branch: master
    
 - provider: s3
   access_key_id:
     secure: RY4Ibctdr/020yuDcghXzcgBuwLVfBZbRUD6d5GkUHLIRSoV0Ylww8IKHg7nZRFoI5HcqhXB5jAEf/MDEKDddnqBLyJDapqohxk2lHe3tkTe42dyfoRz6bIKqoTWgtxTu7mZNILYZ8hba5ENLhGHKUszbIphCIXBnDhmBO9Hjcomv8YNG0zIiCJZ/ZD6vRaehHDfIVJZVHw8z00pfyByNbWCsJIME4/+NAXKbqjyddlV/5OXdeyP5/YuRTT1S72uFK8DfQ54gJkV/j/afhFPs5HP5KEFNUAldYSz0ADq0EWXSKXIhwjzibTtMN8nF8R7kIJu5LRMCwKZxNP05vSl7ZJbUKP3El9lTzydDGES/u/9YW++u6ff6vHo8wcJ04znU6rB9n5CurqKkRu49pY2uJhNFCJm9JJROotwOpddCyAuB1UVehTZj8qfezIG7aDdBtdS6ASGSIQms0+9S2k0gf+T16WZijQ8h3ksqEj4Cd6Nkx8X7uuFUJl+oBXt/ZQXIpx/0smQw2C6SX8aWH6ULh8The2HSkA8oeVb5InM3nRlifn/QFvXlXFtGo5TcTLc50p3goHufOlNfNoTYqen55vpsoELB918zrC7ZjfG/4pPEDFhkJOMfSacfrGuQ3Ecrebu9yI7CKwUzp/9YF2OJnoxA/fAw4mmkFLwl3/bI1E=
   secret_access_key:
     secure: J8fFryEMB3t1QxafOLoZpDpKRmpJWDESq525l6Ozdvy8rrhz6bIxRGZYgLe8mbciZWaSgYo4MM/k1ovWm/ibidmibmLDcRt+QQqezBYLBDg6Gs13Yn6kgdjEvIFxEeAYNcxax0fGBPZnaKAMgGx9XP4bwWuNxEoZKDrC/HcQE8qifmnXFPUw+pIcseTnb5fqAIZfu1IM9QXNgHYjUP1zW9C7A3DtzoJgNtkuB/DkPp6QxkEoro0AufHOKD1Dli2z8D9wDvZWNIWndyjchbmCzk7FrBrUKFkbAi6EeSU6ZSEa7Hn0maQU1YZhuZANp5LXnxxq5SlcVjF9FhyV6O+A+I1TnNu9gmww7gfS0ZSwp2b/6j2d92/BKRp1J+64jpPXSjfAIstbIJQWSCfd0fogwIFjpzZ0/z86dngmMKJJcA4HXA73NypBhh0CVDBkK1lYFl5s095OPLTZ9qNSJjYaXm7k45fy9o+NhPXDdLECog+72vKd89sCTnFt57LHHP32lYD6WBNDrx3W/e2Tn5jlvhKj7p9T5PHfbKEPquetj9NgZkjCleJ4X9QoUOg2jO0ctwu2OGOwVRTIz/gAK6NIOvGaY3RocmkvPcoY4xJz9xQv9/Og50qkPK9mpuY1g/zwGIBc72doDSOp90h8G5/zhEiMPgp4FNUlCwybmIIaN8s=
   bucket:
     secure: M4LsdUF4xuJ7jY8d+i709ZpdJLzsnoHjccbHwUd4JYxPRh6292IJA2LEcIuOSV2ySWTHWvQnp1rPeQP5UO4vSngh0PmZtMh9Ch9EMNXXV9UrD2vghtq+NJLewWGNn6wkxV3I2EsixrFqo8008LEQdPt7GtIAz0kbhnQEjjSVrND/acGL0286oJFvQfw997wzhGnH7pSEPF4PDTEnYevn3XXZQFxplzIgcmu43t+DgDwNy89WXuZtZYyhe/dEN3NnDqtMs+10eWeciS21ygHR/h+Q4p7fXI9Q1lO705bS//lV7s+M7mm8BL5ppWBkKxjkckN3oPYtQGlUInOXh3JQQAbG7jJFBdRwa18FlsN8LwnSMFJAH1e9Nd88RWem/DynwvAhFJ5iWUJN8tBsx9djyukqxhEOuMC3x5QAODIZhwraarsP7LUZPR+SriB8KAOMzX+WNZEGRLIp3yIJN4J3McrUKDAVh7Em7q80Kpnf9kf7mCfidCXVQ1XC7b8HnLESNDtNwb1GtteNBfLUq3R04TJJ6vGedOVAJbDTrTDcTg4//qezuf6ICfcITV9gJNP1YfSuBHLV+sgqkUYvPCsKvizfUZmoupobG4G+RT+cDAiIfBe9/Ja8NrHUWdKzKeXXjOpnx3cPqIuvXfVs0bwepusCs9g2dOcvWVvDY2cmh90=
   region: eu-west-1
   local-dir: target/site
   upload-dir: $TRAVIS_BRANCH/poacc/upgrade-3
   acl: public_read
   skip_cleanup: true
   on:
    repo: OpenPEPPOL/poacc-upgrade-3
    all_branches: true
    condition: $TRAVIS_BRANCH != 'master'
